-- VISUALIZANDO A TABELA
SHOW TABLES;

-- CONFERINDO A ESTRUTURA DA TABELA
DESC CLIENTES;

-- INSERINDO DADOS
INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

-- TRAZENDO DADOS DA TABELA
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT   EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;
SELECT   EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

-- FILTRANDO DADOS DA TABELA COM WHERE
SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

-- FILTRANDO DADOS DA TABELA COM WHERE E UTILIZANDO O LIKE
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

-- FILTRANDO DADOS DA TABELA COM WHERE E UTILIZANDO O LIKE E ADCIONANDO ALGUNS CARACTERS
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

